// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgp97Tu9rvu1R1IaTXXfOE_VUdMQbAF-4',
    appId: '1:865070748461:web:b72861a4568677a9a7b9a4',
    messagingSenderId: '865070748461',
    projectId: 'chat-app-bbd11',
    authDomain: 'chat-app-bbd11.firebaseapp.com',
    storageBucket: 'chat-app-bbd11.appspot.com',
    measurementId: 'G-6Z4MBEGY9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZEMMykO6L8TbRJIUN8WkhO-x69vzDAs',
    appId: '1:865070748461:android:ba1e90a0ff0c573ba7b9a4',
    messagingSenderId: '865070748461',
    projectId: 'chat-app-bbd11',
    storageBucket: 'chat-app-bbd11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWcq53GGPdMyWTnOlgoo7bVcZFh-FHoto',
    appId: '1:865070748461:ios:c287bb623bbbd7a7a7b9a4',
    messagingSenderId: '865070748461',
    projectId: 'chat-app-bbd11',
    storageBucket: 'chat-app-bbd11.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}